/* eslint-disable @typescript-eslint/no-duplicate-enum-values */

export const enum ESCPOSConst {
}

/* [ ] Copy constants from iOS API reference
export type ESCPOSPrinterConnectType =
  | ESCPOSConst.CMP_PORT_Bluetooth
  | ESCPOSConst.CMP_PORT_Bluetooth_Insecure
  | ESCPOSConst.CMP_PORT_WiFi
  | ESCPOSConst.CMP_PORT_USB
  | ESCPOSConst.CMP_PORT_SNMP;

export type ESCPOSPrinterStatus =
  | ESCPOSConst.CMP_STS_PRINTEROFF
  | ESCPOSConst.CMP_STS_MSR_READ
  | ESCPOSConst.CMP_STS_PAPER_EMPTY
  | ESCPOSConst.CMP_STS_COVER_OPEN
  | ESCPOSConst.CMP_STS_BATTERY_LOW
  | ESCPOSConst.CMP_STS_PAPER_NEAREMPTY
  | ESCPOSConst.CMP_STS_DRAWER_LEVEL_H
  | ESCPOSConst.CMP_STS_ONPRESENTER;

export type ESCPOSPrinterErrorCodeExtended =
  | ESCPOSConst.CMP_EX_DEV_NO_PRINTER
  | ESCPOSConst.CMP_EX_DEV_OPEN_ERROR
  | ESCPOSConst.CMP_EX_DEV_SEND_ERROR
  | ESCPOSConst.CMP_EX_DEV_NO_RESPONSE;

export type ESCPOSPrinterPrintAlignment =
  | ESCPOSConst.CMP_ALIGNMENT_LEFT
  | ESCPOSConst.CMP_ALIGNMENT_CENTER
  | ESCPOSConst.CMP_ALIGNMENT_RIGHT;

export type ESCPOSPrinterTextAttribute =
  | ESCPOSConst.CMP_FNT_DEFAULT
  | ESCPOSConst.CMP_FNT_FONTB
  | ESCPOSConst.CMP_FNT_FONTC
  | ESCPOSConst.CMP_FNT_BOLD
  | ESCPOSConst.CMP_FNT_REVERSE
  | ESCPOSConst.CMP_FNT_UNDERLINE;

export type ESCPOSPrinterTextSize =
  | ESCPOSConst.CMP_TXT_1WIDTH
  | ESCPOSConst.CMP_TXT_2WIDTH
  | ESCPOSConst.CMP_TXT_3WIDTH
  | ESCPOSConst.CMP_TXT_4WIDTH
  | ESCPOSConst.CMP_TXT_5WIDTH
  | ESCPOSConst.CMP_TXT_6WIDTH
  | ESCPOSConst.CMP_TXT_7WIDTH
  | ESCPOSConst.CMP_TXT_8WIDTH
  | ESCPOSConst.CMP_TXT_1HEIGHT
  | ESCPOSConst.CMP_TXT_2HEIGHT
  | ESCPOSConst.CMP_TXT_3HEIGHT
  | ESCPOSConst.CMP_TXT_4HEIGHT
  | ESCPOSConst.CMP_TXT_5HEIGHT
  | ESCPOSConst.CMP_TXT_6HEIGHT
  | ESCPOSConst.CMP_TXT_7HEIGHT
  | ESCPOSConst.CMP_TXT_8HEIGHT;

export type ESCPOSPrinterSide =
  | ESCPOSConst.CMP_SIDE_LEFT
  | ESCPOSConst.CMP_SIDE_RIGHT;

export type ESCPOSPrinterTypeface =
  | "DEFAULT"
  | "DEFAULT_BOLD"
  | "MONOSPACE"
  | "SERIF"
  | "SANS_SERIF";

export type ESCPOSPrinterFontStyle =
  | ESCPOSConst.CMP_FNT_DEFAULT
  | ESCPOSConst.CMP_FNT_BOLD
  | ESCPOSConst.CMP_FNT_REVERSE
  | ESCPOSConst.CMP_FNT_UNDERLINE
  | ESCPOSConst.CMP_FNT_ITALIC
  | ESCPOSConst.CMP_FNT_STRIKEOUT;

export type ESCPOSPrinterBitmapMode =
  | ESCPOSConst.CMP_BM_MODE_HT_THRESHOLD
  | ESCPOSConst.CMP_BM_MODE_HT_DITHER
  | ESCPOSConst.CMP_BM_MODE_CMD_RASTER
  | ESCPOSConst.CMP_BM_MODE_CMD_BITIMAGE
  | ESCPOSConst.CMP_BM_MODE_CMD_GRAY16
  | ESCPOSConst.CMP_BM_MODE_CMD_GRAY16DOWNLOAD;

export type ESCPOSPrinterNVImageMode =
  | ESCPOSConst.CMP_BM_MODE_HT_THRESHOLD
  | ESCPOSConst.CMP_BM_MODE_HT_DITHER
  | ESCPOSConst.CMP_BM_MODE_CMD_MONO
  | ESCPOSConst.CMP_BM_MODE_CMD_GRAY16;

export type ESCPOSPrinterBarcodeType =
  | ESCPOSConst.CMP_BCS_UPCA
  | ESCPOSConst.CMP_BCS_UPCE
  | ESCPOSConst.CMP_BCS_EAN8
  | ESCPOSConst.CMP_BCS_JAN8
  | ESCPOSConst.CMP_BCS_EAN13
  | ESCPOSConst.CMP_BCS_JAN13
  | ESCPOSConst.CMP_BCS_ITF
  | ESCPOSConst.CMP_BCS_Codabar
  | ESCPOSConst.CMP_BCS_Code39
  | ESCPOSConst.CMP_BCS_Code93
  | ESCPOSConst.CMP_BCS_Code128
  | ESCPOSConst.CMP_BCS_GS1DATABAR
  | ESCPOSConst.CMP_BCS_GS1DATABAR_E
  | ESCPOSConst.CMP_BCS_GS1DATABAR_T
  | ESCPOSConst.CMP_BCS_GS1DATABAR_L;

export type ESCPOSPrinterTextPosition =
  | ESCPOSConst.CMP_HRI_TEXT_NONE
  | ESCPOSConst.CMP_HRI_TEXT_ABOVE
  | ESCPOSConst.CMP_HRI_TEXT_BELOW;

export type ESCPOSPrinterPDF417ECLevel =
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_0
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_1
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_2
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_3
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_4
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_5
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_6
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_7
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_8;

export type ESCPOSPrinterQRCodeECLevel =
  | ESCPOSConst.CMP_QRCODE_EC_LEVEL_L
  | ESCPOSConst.CMP_QRCODE_EC_LEVEL_M
  | ESCPOSConst.CMP_QRCODE_EC_LEVEL_Q
  | ESCPOSConst.CMP_QRCODE_EC_LEVEL_H;

export type ESCPOSPrinterGS1DatabarType =
  | ESCPOSConst.CMP_BCS_GS1DATABAR_S
  | ESCPOSConst.CMP_BCS_GS1DATABAR_E_S
  | ESCPOSConst.CMP_BCS_GS1DATABAR_S_O;

export type ESCPOSPrinterCutType =
  | ESCPOSConst.CMP_CUT_FULL
  | ESCPOSConst.CMP_CUT_PARTIAL
  | ESCPOSConst.CMP_CUT_FULL_PREFEED
  | ESCPOSConst.CMP_CUT_PARTIAL_PREFEED;

export type ESCPOSPrinterMarkFeedType =
  | ESCPOSConst.CMP_MF_TO_CUTTER
  | ESCPOSConst.CMP_MF_TO_NEXT_TOF;

export type ESCPOSPrinterDrawer =
  | ESCPOSConst.CMP_DRAWER_1
  | ESCPOSConst.CMP_DRAWER_2;

export type ESCPOSPrinterTransactionControl =
  | ESCPOSConst.CMP_TP_NORMAL
  | ESCPOSConst.CMP_TP_TRANSACTION;

export type ESCPOSPrinterRotation =
  | ESCPOSConst.CMP_RP_ROTATE180
  | ESCPOSConst.CMP_RP_BARCODE
  | ESCPOSConst.CMP_RP_BITMAP
  | ESCPOSConst.CMP_RP_NORMAL;

export type ESCPOSPrinterPageModeControl =
  | ESCPOSConst.CMP_PM_PAGE_MODE
  | ESCPOSConst.CMP_PM_PRINT_SAVE
  | ESCPOSConst.CMP_PM_NORMAL
  | ESCPOSConst.CMP_PM_CANCEL;

export type ESCPOSPrinterPageModePrintDirection =
  | ESCPOSConst.CMP_PD_LEFT_TO_RIGHT
  | ESCPOSConst.CMP_PD_BOTTOM_TO_TOP
  | ESCPOSConst.CMP_PD_RIGHT_TO_LEFT
  | ESCPOSConst.CMP_PD_TOP_TO_BOTTOM;

export type ESCPOSPrinterMapMode =
  | ESCPOSConst.CMP_MM_DOTS
  | ESCPOSConst.CMP_MM_TWIPS
  | ESCPOSConst.CMP_MM_ENGLISH
  | ESCPOSConst.CMP_MM_METRIC;

export type ESCPOSPrinterWatermarkStart =
  | ESCPOSConst.CMP_WM_START
  | ESCPOSConst.CMP_WM_STOP;

export type ESCPOSPrinterSearchType =
  | ESCPOSConst.CMP_PORT_Bluetooth
  | ESCPOSConst.CMP_PORT_Bluetooth_Insecure
  | ESCPOSConst.CMP_PORT_WiFi;
*/

export type EpsonPrinerInfo =
  | EpsonPrinerBluetoothInfo
  | EpsonPrinerWiFiInfo;

export type EpsonPrinerWiFiInfo = {
  ipAddress: string;
  macAddress: string;
};

export type EpsonPrinerBluetoothInfo = {
  deviceName: string;
  bdAddress: string;
};
