name: Lint

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Linting
        run: yarn lint
        working-directory: ${{ inputs.working-directory }}
