name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
      - "*.x"

defaults:
  run:
    working-directory: workspaces/react-native-epson-escposprinter

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Linting
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Testing
        run: yarn test --maxWorkers=2 --coverage

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |-
          cp ../../README.md .
          cp ../../LICENSE .
          yarn workspace react-native-epson-escposprinter semantic-release
