name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
      - "*.x"

defaults:
  run:
    working-directory: workspaces/react-native-epson-escposprinter

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      working-directory: workspaces/react-native-epson-escposprinter

  test:
    uses: ./.github/workflows/test.yml
    with:
      working-directory: workspaces/react-native-epson-escposprinter

  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |-
          cp ../../README.md .
          cp ../../LICENSE .
          yarn workspace react-native-epson-escposprinter semantic-release
