name: Test

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Testing
        run: yarn test --maxWorkers=2 --coverage
        working-directory: ${{ inputs.working-directory }}
